--http://jeanmazuelos.com/blog/20131102/oracle-database-server-express-edition-11g
CREATE USER DB_SEMILLERO IDENTIFIED BY 1234 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

GRANT ALL PRIVILEGES to
DB_SEMILLERO;
