-- Tabla que regisra la informacion de una persona
CREATE TABLE PERSONAS (
  PER_ID NUMBER(3,0) NOT NULL ENABLE,
  PER_NOMBRE VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  PER_TIPO_DOCUMENTO VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  PER_NUM_DOCUMENTO VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  PER_NACIMIENTO DATE NOT NULL ENABLE, 
  CONSTRAINT "PERSONAS_PK" PRIMARY KEY ("PER_ID") ENABLE
)
CREATE SEQUENCE "DB_SEMILLERO"."SEQ_PERSONA" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;

-- Tabla que regisra la información de una compra
CREATE TABLE COMPRA (
  COMPRA_ID NUMBER(3,0) NOT NULL ENABLE,
  COMPRA_FECHA DATE NOT NULL ENABLE, 
  PER_ID_FK NUMBER(3,0) NOT NULL ENABLE,
  CONSTRAINT "COMPRA_PK" PRIMARY KEY ("COMPRA_ID") ENABLE,
  CONSTRAINT "COMPRA_FK1" FOREIGN KEY ("PER_ID_FK") REFERENCES PERSONAS("PER_ID") ENABLE
)
CREATE SEQUENCE "DB_SEMILLERO"."SEQ_COMPRA" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;

-- Tabla que registra el detalle de una compra, es decir los items que componen una determinada compra 
CREATE TABLE DETALLE_COMPRA
(
  "ID_COMPRA" NUMBER(3,0) NOT NULL ENABLE,
  "ID_COMIC" NUMBER(3,0) NOT NULL ENABLE,
  CONSTRAINT "DETALLE_COMPRA_PK" PRIMARY KEY ("ID_COMPRA", "ID_COMIC"),
  CONSTRAINT "DETALLE_COMPRA_FK1" FOREIGN KEY ("ID_COMPRA") REFERENCES PERSONAS ("PER_ID") ENABLE,
  CONSTRAINT "DETALLE_COMPRA_FK2" FOREIGN KEY ("ID_COMIC") REFERENCES COMIC ("SCID") ENABLE
)

-- Insercion de datos
INSERT INTO PERSONAS (PER_ID, PER_NOMBRE, PER_TIPO_DOCUMENTO, PER_NUM_DOCUMENTO, PER_NACIMIENTO) 
  VALUES (SEQ_PERSONA.nextval, 'Luis Naranjo', 'CC', '1068669733', TO_DATE('1996-11-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO COMPRA (COMPRA_ID, COMPRA_FECHA, PER_ID_FK) 
  VALUES (SEQ_COMPRA.nextval, TO_DATE('2019-12-20 00:45:13', 'YYYY-MM-DD HH24:MI:SS'), '2')

INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_COMIC)
  VALUES ('2', '1')